version: '3.8'

services:
  backend:
    build: #builds the docker image locally
      context: ./server
      dockerfile: Dockerfile.prod 
    image: aj09/drone-nodejs
#    platform: linux/arm64
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production


  frontend:
    build: #builds the docker image locally
      context: ./client
      dockerfile: Dockerfile.prod
    image: aj09/drone-react
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
